# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fin',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
