# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductElectronics',
            fields=[
                ('modelName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('iventory', models.IntegerField()),
                ('isActive', models.BooleanField(default=1)),
                ('selledCount', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('orderId', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=125)),
                ('modelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ProductElectronics')),
            ],
        ),
    ]
