# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_productelectronics_productorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='productelectronics',
            name='lastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 19, 13, 7, 859000)),
        ),
        migrations.AddField(
            model_name='productorders',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 19, 13, 7, 860000)),
        ),
        migrations.AlterField(
            model_name='productelectronics',
            name='selledCount',
            field=models.IntegerField(),
        ),
    ]
