# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170903_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorders',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productelectronics',
            name='lastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 19, 15, 50, 876000)),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 19, 15, 50, 877000)),
        ),
    ]
