# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170903_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorders',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productelectronics',
            name='lastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 20, 43, 34, 80000)),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 20, 43, 34, 81000)),
        ),
    ]
