# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20170913_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transBundleId', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('transIds', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=40, null=True)),
                ('transTime', models.DateTimeField(default=datetime.datetime(2017, 12, 2, 15, 27, 57, 282000))),
            ],
        ),
        migrations.AddField(
            model_name='productorders',
            name='transId',
            field=models.CharField(default='tx1234', max_length=32),
        ),
        migrations.AlterField(
            model_name='productelectronics',
            name='lastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 15, 27, 57, 280000)),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 15, 27, 57, 281000)),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
